version: '3.5'

services:

    symfony:
      build:
        context: .
        dockerfile: .docker/Dockerfile
      ports:
        - 9991:80
      volumes:
        - ./app:/var/www/public
        - ./logs:/var/log/
        - ./.docker/home:/home/docker
        - ./.docker/apache2/vhosts/vhost.conf:/etc/apache2/sites-enabled/vhost.conf
        - ./.docker/php/php-overwrite.ini:/usr/local/etc/php/conf.d/zz-overwrite.ini

    db:
      image: mysql:5.6
      platform: linux/x86_64
      ports:
        - 44563:3306
      environment:
        MYSQL_DATABASE: db
        MYSQL_USER: dbuser
        MYSQL_PASSWORD: dbpass
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./.docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        - ./.docker/mysql/data:/var/lib/mysql